In [62]:
%pip install matplotlib numpy scikit-learn pandas --quiet

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.1.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [63]:
# Package imports
# import matplotlib
# import matplotlib.pyplot as plt
# import sklearn
# import sklearn.datasets
import pandas as pd
import numpy as np

# Task 1 Implement Logistic Regression

In [160]:
# Prediction function
def predict(Xi, W, b):
    z = np.dot(Xi, W) + b
    y_hat = 1 / (1 + np.exp(-z))
    return y_hat

In [ ]:
# Stochastic Gradient Descent function
def stochastic_gradient_descent(X, y, W, b, alpha=0.01, max_iters=1000, threshold=1e-4):
    # TODO: Stop with the average cost function change less than threshold
    # TODO: This version does not have loops on backpropagation because it is for just one neuron
    N = X.shape[0]
    stopping = False
    J_running = 0
    J_running_prev = 0
    iteration = 0

    while not stopping:
        # Randomly select one data point #Sample size = 1        
        i_random = np.random.randint(0, high=N)
        y_hat = predict(X[i_random], W, b)
        J_current = - (y[i_random] * np.log(y_hat) + (1 - y[i_random]) * np.log(1 - y_hat))
        error = y_hat - y[i_random]
        
        delta_W = error * X[i_random]
        delta_b = error
        
        W -= alpha * delta_W
        b -= alpha * delta_b

        # Check stopping criteria
        iteration += 1
        J_running += J_current
        if iteration >= max_iters:
            stopping = True
        if iteration % N == 0:
            print("Average cost function over epoch:", J_running / N)
            print("Epoch:", iteration // N, " Cost:", J_running, " Previous Cost:", J_running_prev, "\n")
            print("Difference in cost function:", abs(J_running - J_running_prev))
            if abs(J_running - J_running_prev) < threshold:
                stopping = True
            J_running_prev = J_running
        
    return W, b

# Task 2 Implement Logistic Regression

In [159]:
# Reading data function
def read_data(file_path):
    df = pd.read_csv(file_path)
    y = df['Class'].values   # Labels
    X = df.drop('Class', axis=1).values  # Features
    return X, y

In [183]:
file_path = 'Datasets/blobs600.csv'
# file_path = 'Datasets/circles500.csv'
X, y = read_data(file_path)
# Initialize weights and bias
np.random.seed(3301)
W = np.random.normal(0,0.01,X.shape[1])
b = np.random.normal(0,0.01,1)

# Training the model using Stochastic Gradient Descent
W_trained, b_trained = stochastic_gradient_descent(X, y, W, b, alpha=0.01, max_iters=10000, threshold=1e-4)
print("Trained Weights:", W_trained)
print("Trained Bias:", b_trained)
# Dummy change



Average cost function over epoch: [0.20070638]
Epoch: 1  Cost: [120.42382617]  Previous Cost: 0 

Difference in cost function: [120.42382617]
Average cost function over epoch: [0.27023351]
Epoch: 2  Cost: [162.14010887]  Previous Cost: [162.14010887] 

Difference in cost function: [0.]
Trained Weights: [1.22512157 1.05917837 1.13397491]
Trained Bias: [-0.08444917]


In [171]:
i_random = np.random.randint(0, high=X.shape[0])
Xi = X[i_random]
print(Xi)
print(W)
print(b)

print(np.dot(Xi, W))

y_hat = predict(X[i_random], W, b)
y_hat


# np.dot(Xi, W)

# z = sum(np.dot(Xi, W)) + b
# y_hat = 1 / (1 + np.exp(-z))
# y_hat



[-0.67146559 -1.90740328 -1.25820006]
[ 0.01394912 -0.01221096  0.01272894]
[0.00991508]
-0.0020906842748435236


array([0.50195609])